services:
  nex-api:
    build: .
    image: nex-backend:latest
    container_name: nex-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
      - GOOGLE_CLOUD_PROJECT=neuralexchange-b6b7f
    volumes:
      - ./service_account.json:/app/service_account.json
    networks:
      - nex-network

  caddy:
    image: caddy:alpine
    container_name: nex-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nex-api
    networks:
      - nex-network

networks:
  nex-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
